/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ImportOrderRequestImportedPayment
 */
export interface ImportOrderRequestImportedPayment {
    /**
     * 
     * @type {string}
     * @memberof ImportOrderRequestImportedPayment
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ImportOrderRequestImportedPayment
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {Array<OrderPaymentAmount>}
     * @memberof ImportOrderRequestImportedPayment
     */
    'amounts': Array<OrderPaymentAmount>;
    /**
     * 
     * @type {PaymentCcInfo}
     * @memberof ImportOrderRequestImportedPayment
     */
    'ccInfo'?: PaymentCcInfo;
    /**
     * 
     * @type {boolean}
     * @memberof ImportOrderRequestImportedPayment
     */
    'isUpfront'?: boolean;
}
