/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderRefundAmountCode = {
    Unknown: 'UNKNOWN',
    Ordered: 'ORDERED',
    Shipping: 'SHIPPING'
} as const;
export type OrderRefundAmountCode = typeof OrderRefundAmountCode[keyof typeof OrderRefundAmountCode];


export function OrderRefundAmountCodeFromJSON(json: any): OrderRefundAmountCode {
    return OrderRefundAmountCodeFromJSONTyped(json, false);
}

export function OrderRefundAmountCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRefundAmountCode {
    return json as OrderRefundAmountCode;
}

export function OrderRefundAmountCodeToJSON(value?: OrderRefundAmountCode | null): any {
    return value as any;
}

