/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderDataShipmentInfo
 */
export interface OrderDataShipmentInfo {
    /**
     * 
     * @type {string}
     * @memberof OrderDataShipmentInfo
     */
    'reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataShipmentInfo
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataShipmentInfo
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataShipmentInfo
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataShipmentInfo
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderDataShipmentInfo
     */
    'amount'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderDataShipmentInfo
     */
    'fee'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderDataShipmentInfo
     */
    'vatAmount'?: OrderMoney;
    /**
     * 
     * @type {number}
     * @memberof OrderDataShipmentInfo
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDataShipmentInfo
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDataShipmentInfo
     */
    'vatCalculated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderDataShipmentInfo
     */
    'grn'?: string;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderDataShipmentInfo
     */
    'fromAddress'?: OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderDataShipmentInfo
     */
    'returnAddress'?: OrderPostalAddress;
}
