/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderPaymentFilterCondition = {
    In: 'IN',
    NotIn: 'NOT_IN'
} as const;
export type OrderPaymentFilterCondition = typeof OrderPaymentFilterCondition[keyof typeof OrderPaymentFilterCondition];


export function OrderPaymentFilterConditionFromJSON(json: any): OrderPaymentFilterCondition {
    return OrderPaymentFilterConditionFromJSONTyped(json, false);
}

export function OrderPaymentFilterConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPaymentFilterCondition {
    return json as OrderPaymentFilterCondition;
}

export function OrderPaymentFilterConditionToJSON(value?: OrderPaymentFilterCondition | null): any {
    return value as any;
}

