/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderDataPromotionInfo
 */
export interface OrderDataPromotionInfo {
    /**
     * 
     * @type {string}
     * @memberof OrderDataPromotionInfo
     */
    'promotionGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataPromotionInfo
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataPromotionInfo
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataPromotionInfo
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataPromotionInfo
     */
    'description'?: string;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderDataPromotionInfo
     */
    'amount'?: OrderMoney;
    /**
     * 
     * @type {string}
     * @memberof OrderDataPromotionInfo
     */
    'couponCode'?: string;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderDataPromotionInfo
     */
    'vatAmount'?: OrderMoney;
    /**
     * 
     * @type {number}
     * @memberof OrderDataPromotionInfo
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDataPromotionInfo
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDataPromotionInfo
     */
    'vatCalculated'?: boolean;
}
