/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderPayment
 */
export interface OrderPayment {
    /**
     * 
     * @type {string}
     * @memberof OrderPayment
     */
    'orderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderPayment
     */
    'id'?: string;
    /**
     * payment type stripe, paypal..
     * @type {string}
     * @memberof OrderPayment
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderPayment
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {Array<OrderPaymentAmount>}
     * @memberof OrderPayment
     */
    'amounts'?: Array<OrderPaymentAmount>;
    /**
     * 
     * @type {PaymentCcInfo}
     * @memberof OrderPayment
     */
    'ccInfo'?: PaymentCcInfo;
    /**
     * 
     * @type {Array<OrderTransaction>}
     * @memberof OrderPayment
     */
    'transactions'?: Array<OrderTransaction>;
}
