/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderDataCustomerInfo
 */
export interface OrderDataCustomerInfo {
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'segment'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'certifiedEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'taxCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'sdiCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'fiscalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDataCustomerInfo
     */
    'agentGrn'?: string;
}
