/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderCreateOrderRequest
 */
export interface OrderCreateOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'number': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'market': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'locale': string;
    /**
     * 
     * @type {Array<OrderOrderDataItem>}
     * @memberof OrderCreateOrderRequest
     */
    'items': Array<OrderOrderDataItem>;
    /**
     * 
     * @type {Array<OrderDataPaymentInfo>}
     * @memberof OrderCreateOrderRequest
     */
    'paymentsInfo'?: Array<OrderDataPaymentInfo>;
    /**
     * 
     * @type {Array<OrderDataShipmentInfo>}
     * @memberof OrderCreateOrderRequest
     */
    'shipmentsInfo'?: Array<OrderDataShipmentInfo>;
    /**
     * 
     * @type {Array<OrderDataPromotionInfo>}
     * @memberof OrderCreateOrderRequest
     */
    'promotions'?: Array<OrderDataPromotionInfo>;
    /**
     * 
     * @type {Array<CreateOrderRequestInitialPayment>}
     * @memberof OrderCreateOrderRequest
     */
    'payments'?: Array<CreateOrderRequestInitialPayment>;
    /**
     * 
     * @type {OrderCurrency}
     * @memberof OrderCreateOrderRequest
     */
    'currency': OrderCurrency;
    /**
     * 
     * @type {{ [key: string]: OrderDataSubtotal; }}
     * @memberof OrderCreateOrderRequest
     */
    'subtotals': { [key: string]: OrderDataSubtotal; };
    /**
     * 
     * @type {{ [key: string]: OrderDataTotal; }}
     * @memberof OrderCreateOrderRequest
     */
    'totals': { [key: string]: OrderDataTotal; };
    /**
     * 
     * @type {boolean}
     * @memberof OrderCreateOrderRequest
     */
    'vatIncluded': boolean;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderCreateOrderRequest
     */
    'billingAddress': OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderCreateOrderRequest
     */
    'shippingAddress': OrderPostalAddress;
    /**
     * 
     * @type {OrderDataCustomerInfo}
     * @memberof OrderCreateOrderRequest
     */
    'customerInfo': OrderDataCustomerInfo;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'cartGrn'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrderCreateOrderRequest
     */
    'onHold'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateOrderRequest
     */
    'notes'?: string;
}
