/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderRefund
 */
export interface OrderRefund {
    /**
     * 
     * @type {Date}
     * @memberof OrderRefund
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderRefund
     */
    'paymentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderRefund
     */
    'id'?: string;
    /**
     * 
     * @type {Array<OrderRefundItem>}
     * @memberof OrderRefund
     */
    'items'?: Array<OrderRefundItem>;
    /**
     * 
     * @type {Array<OrderRefundAmount>}
     * @memberof OrderRefund
     */
    'amounts'?: Array<OrderRefundAmount>;
    /**
     * 
     * @type {string}
     * @memberof OrderRefund
     */
    'note'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderRefund
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrderRefund
     */
    'transactionIds'?: Array<string>;
}
