/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderOrderDataItem
 */
export interface OrderOrderDataItem {
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productGrn'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderOrderDataItem
     */
    'qtyOrdered'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderOrderDataItem
     */
    'qtyCommitted'?: number;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'unitSalePrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'unitListPrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'unitBasePrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'unitVatAmount'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'rowSalePrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'rowListPrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'rowVatAmount'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'discountAmount'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'rowBasePrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'unitCustomPrice'?: OrderMoney;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderOrderDataItem
     */
    'rowCustomPrice'?: OrderMoney;
    /**
     * 
     * @type {number}
     * @memberof OrderOrderDataItem
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OrderOrderDataItem
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderOrderDataItem
     */
    'vatCalculated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productName'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productSku'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productOptions'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productImg'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'productData'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDataItem
     */
    'shipmentInfoReference'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrderOrderDataItem
     */
    'promotionGrn'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof OrderOrderDataItem
     */
    'productIsVirtual'?: boolean;
    /**
     * 
     * @type {Array<ItemProductConfigurationStep>}
     * @memberof OrderOrderDataItem
     */
    'productConfiguration'?: Array<ItemProductConfigurationStep>;
}
