/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderCreateRefundTransactionRequest
 */
export interface OrderCreateRefundTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundTransactionRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundTransactionRequest
     */
    'refundId': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundTransactionRequest
     */
    'parentTransactionId'?: string;
    /**
     * 
     * @type {OrderTransactionType}
     * @memberof OrderCreateRefundTransactionRequest
     */
    'type'?: OrderTransactionType;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundTransactionRequest
     */
    'additionalInfo'?: string;
}
