/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderCreatePaymentRequest
 */
export interface OrderCreatePaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderCreatePaymentRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreatePaymentRequest
     */
    'orderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreatePaymentRequest
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreatePaymentRequest
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {OrderMoney}
     * @memberof OrderCreatePaymentRequest
     */
    'amount'?: OrderMoney;
    /**
     * 
     * @type {PaymentCcInfo}
     * @memberof OrderCreatePaymentRequest
     */
    'ccInfo'?: PaymentCcInfo;
}
