/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderImportOrderRequest
 */
export interface OrderImportOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderImportOrderRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {Date}
     * @memberof OrderImportOrderRequest
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderImportOrderRequest
     */
    'number': string;
    /**
     * 
     * @type {string}
     * @memberof OrderImportOrderRequest
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderImportOrderRequest
     */
    'market': string;
    /**
     * 
     * @type {string}
     * @memberof OrderImportOrderRequest
     */
    'locale': string;
    /**
     * 
     * @type {OrderDataCustomerInfo}
     * @memberof OrderImportOrderRequest
     */
    'customerInfo': OrderDataCustomerInfo;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderImportOrderRequest
     */
    'shippingAddress': OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderImportOrderRequest
     */
    'billingAddress': OrderPostalAddress;
    /**
     * 
     * @type {Array<ImportOrderRequestImportedPayment>}
     * @memberof OrderImportOrderRequest
     */
    'payments': Array<ImportOrderRequestImportedPayment>;
    /**
     * 
     * @type {Array<OrderDataPaymentInfo>}
     * @memberof OrderImportOrderRequest
     */
    'paymentsInfo': Array<OrderDataPaymentInfo>;
    /**
     * 
     * @type {Array<OrderDataShipmentInfo>}
     * @memberof OrderImportOrderRequest
     */
    'shipmentsInfo': Array<OrderDataShipmentInfo>;
    /**
     * 
     * @type {Array<OrderOrderDataItem>}
     * @memberof OrderImportOrderRequest
     */
    'items': Array<OrderOrderDataItem>;
    /**
     * 
     * @type {{ [key: string]: OrderDataSubtotal; }}
     * @memberof OrderImportOrderRequest
     */
    'subtotals': { [key: string]: OrderDataSubtotal; };
    /**
     * 
     * @type {{ [key: string]: OrderDataTotal; }}
     * @memberof OrderImportOrderRequest
     */
    'totals': { [key: string]: OrderDataTotal; };
    /**
     * 
     * @type {string}
     * @memberof OrderImportOrderRequest
     */
    'status': string;
    /**
     * 
     * @type {OrderCurrency}
     * @memberof OrderImportOrderRequest
     */
    'currency': OrderCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof OrderImportOrderRequest
     */
    'vatIncluded'?: boolean;
}
