/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderShipment
 */
export interface OrderShipment {
    /**
     * 
     * @type {Date}
     * @memberof OrderShipment
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrderShipment
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderShipment
     */
    'orderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderShipment
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderShipment
     */
    'status'?: string;
    /**
     * 
     * @type {Array<OrderShipmentItem>}
     * @memberof OrderShipment
     */
    'items'?: Array<OrderShipmentItem>;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderShipment
     */
    'address'?: OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderShipment
     */
    'fromAddress'?: OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderShipment
     */
    'returnAddress'?: OrderPostalAddress;
    /**
     * 
     * @type {Array<ShipmentTracking>}
     * @memberof OrderShipment
     */
    'tracking'?: Array<ShipmentTracking>;
    /**
     * 
     * @type {Array<ShipmentTracking>}
     * @memberof OrderShipment
     */
    'returnTracking'?: Array<ShipmentTracking>;
}
