/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderPaymentAmountCode = {
    Unknown: 'UNKNOWN',
    Canceled: 'CANCELED',
    Ordered: 'ORDERED',
    Paid: 'PAID',
    Refunded: 'REFUNDED',
    Authorized: 'AUTHORIZED'
} as const;
export type OrderPaymentAmountCode = typeof OrderPaymentAmountCode[keyof typeof OrderPaymentAmountCode];


export function OrderPaymentAmountCodeFromJSON(json: any): OrderPaymentAmountCode {
    return OrderPaymentAmountCodeFromJSONTyped(json, false);
}

export function OrderPaymentAmountCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPaymentAmountCode {
    return json as OrderPaymentAmountCode;
}

export function OrderPaymentAmountCodeToJSON(value?: OrderPaymentAmountCode | null): any {
    return value as any;
}

