/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderTransactionType = {
    Unknown: 'UNKNOWN',
    Authorization: 'AUTHORIZATION',
    Capture: 'CAPTURE',
    Sale: 'SALE',
    Refund: 'REFUND',
    Void: 'VOID',
    Failed: 'FAILED',
    Pending: 'PENDING',
    Fraud: 'FRAUD'
} as const;
export type OrderTransactionType = typeof OrderTransactionType[keyof typeof OrderTransactionType];


export function OrderTransactionTypeFromJSON(json: any): OrderTransactionType {
    return OrderTransactionTypeFromJSONTyped(json, false);
}

export function OrderTransactionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderTransactionType {
    return json as OrderTransactionType;
}

export function OrderTransactionTypeToJSON(value?: OrderTransactionType | null): any {
    return value as any;
}

