/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderCreateShipmentRequest
 */
export interface OrderCreateShipmentRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderCreateShipmentRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateShipmentRequest
     */
    'orderId': string;
    /**
     * 
     * @type {Array<OrderShipmentItem>}
     * @memberof OrderCreateShipmentRequest
     */
    'items': Array<OrderShipmentItem>;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderCreateShipmentRequest
     */
    'address': OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderCreateShipmentRequest
     */
    'fromAddress'?: OrderPostalAddress;
    /**
     * 
     * @type {OrderPostalAddress}
     * @memberof OrderCreateShipmentRequest
     */
    'returnAddress'?: OrderPostalAddress;
    /**
     * 
     * @type {Array<ShipmentTracking>}
     * @memberof OrderCreateShipmentRequest
     */
    'tracking'?: Array<ShipmentTracking>;
    /**
     * 
     * @type {Array<ShipmentTracking>}
     * @memberof OrderCreateShipmentRequest
     */
    'returnTracking'?: Array<ShipmentTracking>;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateShipmentRequest
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateShipmentRequest
     */
    'method'?: string;
}
