/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderStatusFilterCondition = {
    In: 'IN',
    NotIn: 'NOT_IN'
} as const;
export type OrderStatusFilterCondition = typeof OrderStatusFilterCondition[keyof typeof OrderStatusFilterCondition];


export function OrderStatusFilterConditionFromJSON(json: any): OrderStatusFilterCondition {
    return OrderStatusFilterConditionFromJSONTyped(json, false);
}

export function OrderStatusFilterConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStatusFilterCondition {
    return json as OrderStatusFilterCondition;
}

export function OrderStatusFilterConditionToJSON(value?: OrderStatusFilterCondition | null): any {
    return value as any;
}

