/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderCreateRefundRequest
 */
export interface OrderCreateRefundRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundRequest
     */
    'paymentId': string;
    /**
     * 
     * @type {Array<OrderRefundItem>}
     * @memberof OrderCreateRefundRequest
     */
    'items'?: Array<OrderRefundItem>;
    /**
     * 
     * @type {Array<OrderRefundAmount>}
     * @memberof OrderCreateRefundRequest
     */
    'amounts': Array<OrderRefundAmount>;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundRequest
     */
    'note'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRefundRequest
     */
    'additionalInfo'?: string;
}
