/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PaymentCcInfo
 */
export interface PaymentCcInfo {
    /**
     * 
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'approval'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentCcInfo
     */
    'expMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'expYear'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'last4'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'numberEnc'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'owner'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'avsStatus'?: string;
    /**
     * card type MasterCard, Visa..
     * @type {string}
     * @memberof PaymentCcInfo
     */
    'type'?: string;
}
