/* tslint:disable */
/* eslint-disable */
/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductConfigurationStepOption
 */
export interface ProductConfigurationStepOption {
    /**
     * 
     * @type {string}
     * @memberof ProductConfigurationStepOption
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductConfigurationStepOption
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductConfigurationStepOption
     */
    'label'?: string;
    /**
     * 
     * @type {OrderMoney}
     * @memberof ProductConfigurationStepOption
     */
    'priceVariation'?: OrderMoney;
    /**
     * 
     * @type {OptionImage}
     * @memberof ProductConfigurationStepOption
     */
    'image'?: OptionImage;
    /**
     * 
     * @type {boolean}
     * @memberof ProductConfigurationStepOption
     */
    'hasQuantity'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductConfigurationStepOption
     */
    'quantity'?: number;
}
