/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPaymentAmount } from '../models/OrderPaymentAmount';
import { PaymentCcInfo } from '../models/PaymentCcInfo';
import { HttpFile } from '../http/http';

export class ImportOrderRequestImportedPayment {
    'code': string;
    'additionalInfo'?: string;
    'amounts': Array<OrderPaymentAmount>;
    'ccInfo'?: PaymentCcInfo;
    'isUpfront'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "amounts",
            "baseName": "amounts",
            "type": "Array<OrderPaymentAmount>",
            "format": ""
        },
        {
            "name": "ccInfo",
            "baseName": "ccInfo",
            "type": "PaymentCcInfo",
            "format": ""
        },
        {
            "name": "isUpfront",
            "baseName": "isUpfront",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImportOrderRequestImportedPayment.attributeTypeMap;
    }

    public constructor() {
    }
}

