/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductConfigurationStepOption } from '../models/ProductConfigurationStepOption';
import { HttpFile } from '../http/http';

export class ItemProductConfigurationStep {
    'id'?: string;
    'grn'?: string;
    'label'?: string;
    'description'?: string;
    'options'?: Array<ProductConfigurationStepOption>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<ProductConfigurationStepOption>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemProductConfigurationStep.attributeTypeMap;
    }

    public constructor() {
    }
}

