/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderTransactionType } from '../models/OrderTransactionType';
import { HttpFile } from '../http/http';

export class OrderTransaction {
    'createdAt'?: Date;
    'paymentId'?: string;
    'id'?: string;
    'type'?: OrderTransactionType;
    'additionalInfo'?: string;
    'childTransactions'?: Array<OrderTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OrderTransactionType",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "childTransactions",
            "baseName": "childTransactions",
            "type": "Array<OrderTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}



