/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPaymentFilterCondition } from '../models/OrderPaymentFilterCondition';
import { HttpFile } from '../http/http';

export class OrderPaymentFilter {
    'codes'?: Array<string>;
    'condition'?: OrderPaymentFilterCondition;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "codes",
            "baseName": "codes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "OrderPaymentFilterCondition",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPaymentFilter.attributeTypeMap;
    }

    public constructor() {
    }
}



