/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderLocalizedText } from '../models/OrderLocalizedText';
import { OrderMoney } from '../models/OrderMoney';
import { HttpFile } from '../http/http';

export class OrderDataPaymentInfo {
    'code': string;
    'additionalInfo'?: string;
    'amount': OrderMoney;
    'fee'?: OrderMoney;
    'vatAmount'?: OrderMoney;
    'vatPercentage'?: number;
    'vatInaccurate'?: boolean;
    'vatCalculated'?: boolean;
    'title'?: OrderLocalizedText;
    'label'?: OrderLocalizedText;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "OrderMoney",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "OrderMoney",
            "format": ""
        },
        {
            "name": "vatAmount",
            "baseName": "vatAmount",
            "type": "OrderMoney",
            "format": ""
        },
        {
            "name": "vatPercentage",
            "baseName": "vatPercentage",
            "type": "number",
            "format": "float"
        },
        {
            "name": "vatInaccurate",
            "baseName": "vatInaccurate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vatCalculated",
            "baseName": "vatCalculated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "OrderLocalizedText",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "OrderLocalizedText",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderDataPaymentInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

