/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PrintOrdersLabelsResponseFailedOrder } from '../models/PrintOrdersLabelsResponseFailedOrder';
import { HttpFile } from '../http/http';

export class OrderPrintOrdersLabelsResponse {
    'downloadUrl'?: string;
    'failedOrders'?: Array<PrintOrdersLabelsResponseFailedOrder>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "downloadUrl",
            "baseName": "downloadUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "failedOrders",
            "baseName": "failedOrders",
            "type": "Array<PrintOrdersLabelsResponseFailedOrder>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPrintOrdersLabelsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

