/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderFulfillment } from '../models/OrderFulfillment';
import { HttpFile } from '../http/http';

export class OrderListFulfillmentsResponse {
    'fulfillments'?: Array<OrderFulfillment>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fulfillments",
            "baseName": "fulfillments",
            "type": "Array<OrderFulfillment>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderListFulfillmentsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

