/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderTransactionType } from '../models/OrderTransactionType';
import { HttpFile } from '../http/http';

export class OrderCreateRefundTransactionRequest {
    'tenantId'?: string;
    'refundId'?: string;
    'parentTransactionId'?: string;
    'type'?: OrderTransactionType;
    'additionalInfo'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "refundId",
            "baseName": "refundId",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentTransactionId",
            "baseName": "parentTransactionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OrderTransactionType",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCreateRefundTransactionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



