/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderFulfillmentItem } from '../models/OrderFulfillmentItem';
import { HttpFile } from '../http/http';

export class OrderFulfillment {
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'orderId'?: string;
    'id'?: string;
    'status'?: string;
    'items'?: Array<OrderFulfillmentItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderFulfillmentItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderFulfillment.attributeTypeMap;
    }

    public constructor() {
    }
}

