/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderMoney } from '../models/OrderMoney';
import { PaymentCcInfo } from '../models/PaymentCcInfo';
import { HttpFile } from '../http/http';

export class OrderCreatePaymentRequest {
    'tenantId'?: string;
    'orderId'?: string;
    'code'?: string;
    'additionalInfo'?: string;
    'amount'?: OrderMoney;
    'ccInfo'?: PaymentCcInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "OrderMoney",
            "format": ""
        },
        {
            "name": "ccInfo",
            "baseName": "ccInfo",
            "type": "PaymentCcInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCreatePaymentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

