/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderMoney } from '../models/OrderMoney';
import { OrderRefundAmountCode } from '../models/OrderRefundAmountCode';
import { HttpFile } from '../http/http';

export class OrderRefundAmount {
    'code'?: OrderRefundAmountCode;
    'value'?: OrderMoney;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "OrderRefundAmountCode",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "OrderMoney",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderRefundAmount.attributeTypeMap;
    }

    public constructor() {
    }
}



