/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPaymentAmount } from '../models/OrderPaymentAmount';
import { OrderTransaction } from '../models/OrderTransaction';
import { PaymentCcInfo } from '../models/PaymentCcInfo';
import { HttpFile } from '../http/http';

export class OrderPayment {
    'orderId'?: string;
    'id'?: string;
    'code'?: string;
    'additionalInfo'?: string;
    'amounts'?: Array<OrderPaymentAmount>;
    'ccInfo'?: PaymentCcInfo;
    'transactions'?: Array<OrderTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "amounts",
            "baseName": "amounts",
            "type": "Array<OrderPaymentAmount>",
            "format": ""
        },
        {
            "name": "ccInfo",
            "baseName": "ccInfo",
            "type": "PaymentCcInfo",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<OrderTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPayment.attributeTypeMap;
    }

    public constructor() {
    }
}

