/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderDataCustomerInfo {
    'grn'?: string;
    'firstname'?: string;
    'lastname'?: string;
    'email'?: string;
    'phone'?: string;
    'segment'?: string;
    'data'?: string;
    'certifiedEmail'?: string;
    'taxCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstname",
            "baseName": "firstname",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastname",
            "baseName": "lastname",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "segment",
            "baseName": "segment",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "certifiedEmail",
            "baseName": "certifiedEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxCode",
            "baseName": "taxCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderDataCustomerInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

