/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderMoney } from '../models/OrderMoney';
import { HttpFile } from '../http/http';

export class OrderDataPromotionInfo {
    'promotionGrn'?: string;
    'type'?: string;
    'additionalInfo'?: string;
    'name'?: string;
    'description'?: string;
    'amount'?: OrderMoney;
    'couponCode'?: string;
    'vatAmount'?: OrderMoney;
    'vatPercentage'?: number;
    'vatInaccurate'?: boolean;
    'vatCalculated'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "promotionGrn",
            "baseName": "promotionGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "OrderMoney",
            "format": ""
        },
        {
            "name": "couponCode",
            "baseName": "couponCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "vatAmount",
            "baseName": "vatAmount",
            "type": "OrderMoney",
            "format": ""
        },
        {
            "name": "vatPercentage",
            "baseName": "vatPercentage",
            "type": "number",
            "format": "float"
        },
        {
            "name": "vatInaccurate",
            "baseName": "vatInaccurate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vatCalculated",
            "baseName": "vatCalculated",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderDataPromotionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

