/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderRefundItem } from '../models/OrderRefundItem';
import { HttpFile } from '../http/http';

export class OrderCalculateRefundRequest {
    'tenantId'?: string;
    'paymentId'?: string;
    'items'?: Array<OrderRefundItem>;
    /**
    * Boolean indicating whether to calculate refund for shipping.
    */
    'shipping'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderRefundItem>",
            "format": ""
        },
        {
            "name": "shipping",
            "baseName": "shipping",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCalculateRefundRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

