/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPostalAddress } from '../models/OrderPostalAddress';
import { OrderShipmentItem } from '../models/OrderShipmentItem';
import { HttpFile } from '../http/http';

export class OrderCreateShipmentRequest {
    'tenantId'?: string;
    'orderId'?: string;
    'items'?: Array<OrderShipmentItem>;
    'address'?: OrderPostalAddress;
    'fromAddress'?: OrderPostalAddress;
    'returnAddress'?: OrderPostalAddress;
    'code'?: string;
    'method'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderShipmentItem>",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "OrderPostalAddress",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "OrderPostalAddress",
            "format": ""
        },
        {
            "name": "returnAddress",
            "baseName": "returnAddress",
            "type": "OrderPostalAddress",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCreateShipmentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

