/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ShipmentTracking {
    'carrierCode'?: string;
    'carrierTitle'?: string;
    'url'?: string;
    'number'?: string;
    'labelUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "carrierCode",
            "baseName": "carrierCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "carrierTitle",
            "baseName": "carrierTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "labelUrl",
            "baseName": "labelUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShipmentTracking.attributeTypeMap;
    }

    public constructor() {
    }
}

