/**
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPostalAddress } from '../models/OrderPostalAddress';
import { HttpFile } from '../http/http';

export class UpdateOrderRequestPayload {
    'billingAddress'?: OrderPostalAddress;
    'shippingAddress'?: OrderPostalAddress;
    'additionalInfo'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "OrderPostalAddress",
            "format": ""
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "OrderPostalAddress",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateOrderRequestPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

